#!/usr/bin/env python3
# =============================================================================
# Astra Runtime - Paper 1 numbers.tex generator
# scripts/gen_numbers_tex.py
#
# Reads the artefact CSVs produced by run_paper1_sweep.sh and emits a
# LaTeX file that overrides the placeholder \todoNum macros in
# papers/paper1/macros.tex with concrete numbers.
#
# Output goes to stdout; build.sh redirects it to
# papers/paper1/numbers/numbers.tex.
#
# Usage:
#   python3 scripts/gen_numbers_tex.py figure1.csv pool_scaling.csv revocation.csv
# =============================================================================

from __future__ import annotations

import csv
import sys
from pathlib import Path


def loadCsv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open() as f:
        return [r for r in csv.DictReader(f)]


def pickP99(rows: list[dict], transport: str, payload: int) -> float:
    for r in rows:
        if r.get("transport") == transport and \
           int(r.get("payload_bytes", "0") or "0") == payload:
            try:
                return float(r["p99_ns"])
            except (KeyError, ValueError):
                pass
    return 0.0


def pickPool(rows: list[dict], pool: int) -> dict:
    for r in rows:
        try:
            if int(r["pool_active"]) == pool:
                return r
        except (KeyError, ValueError):
            continue
    return {}


def percentileOfRevoke(rows: list[dict], pct: float) -> float:
    nss = []
    for r in rows:
        try:
            nss.append(int(r["window_ns"]))
        except (KeyError, ValueError):
            pass
    if not nss:
        return 0.0
    nss.sort()
    idx = min(int(pct * len(nss)), len(nss) - 1)
    return nss[idx]


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: gen_numbers_tex.py figure1.csv pool_scaling.csv revocation.csv",
              file=sys.stderr)
        return 1

    f1   = loadCsv(Path(sys.argv[1]))
    pool = loadCsv(Path(sys.argv[2]))
    rev  = loadCsv(Path(sys.argv[3]))

    # Reference numbers.
    rawA  = pickP99(f1, "astra_raw",   256)
    gatA  = pickP99(f1, "astra_gated", 256)
    aer   = pickP99(f1, "aeron",       256)
    iour  = pickP99(f1, "io_uring",    256)
    pip   = pickP99(f1, "pipe",        256)

    delta_p99 = max(0.0, gatA - rawA)
    aeron_gap = (gatA - aer) / aer * 100 if aer > 0 else 0

    pool_at_full = pickPool(pool, 4090)
    val_p50   = float(pool_at_full.get("p50_ns",   0))
    val_p99   = float(pool_at_full.get("p99_ns",   0))
    val_p9999 = float(pool_at_full.get("p9999_ns", 0))

    rev_p99_us = percentileOfRevoke(rev, 0.99) / 1000.0

    # Emit overrides. Each \renewcommand wraps the same macro defined
    # in macros.tex with a concrete value.
    print(r"% Auto-generated by scripts/gen_numbers_tex.py — do not edit.")
    print(r"% Re-run build.sh --refresh after a sweep run.")
    def emit(name: str, val: str) -> None:
        print(rf"\renewcommand{{\{name}}}{{{val}}}")
    emit("validateP50",   f"{val_p50:.0f}")
    emit("validateP99",   f"{val_p99:.0f}")
    emit("validateP9999", f"{val_p9999:.0f}")
    emit("rawAstraRTT",   f"{rawA:.0f}")
    emit("gatedAstraRTT", f"{gatA:.0f}")
    emit("aeronRTT",      f"{aer:.0f}")
    emit("iouringRTT",    f"{iour:.0f}")
    emit("pipeRTT",       f"{pip:.0f}")
    emit("gateOverheadP99", f"{delta_p99:.0f}")
    emit("aeronGapPercent", f"{aeron_gap:.1f}")
    emit("revokeP99",       f"{rev_p99_us:.1f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
