#!/usr/bin/env python3
# =============================================================================
# Astra Runtime - Paper 1 numbers.tex generator
# scripts/gen_numbers_tex.py
#
# Reads the artefact CSVs produced by run_paper1_sweep.sh and emits a
# LaTeX file that overrides the placeholder \todoNum macros in
# papers/paper1/macros.tex with concrete numbers.
#
# Output goes to stdout; build.sh redirects it to
# papers/paper1/numbers/numbers.tex.
#
# Usage:
#   python3 scripts/gen_numbers_tex.py figure1.csv pool_scaling.csv revocation.csv
# =============================================================================

from __future__ import annotations

import csv
import sys
from pathlib import Path


def loadCsv(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open() as f:
        return [r for r in csv.DictReader(f)]


def pickP99(rows: list[dict], transport: str, payload: int) -> float:
    for r in rows:
        if r.get("transport") != transport:
            continue
        # Self-skipped baselines emit e.g. "aeron,SKIPPED,0,..." — the
        # payload column is not numeric; treat as absent, never crash.
        try:
            if int(r.get("payload_bytes", "0") or "0") != payload:
                continue
            return float(r["p99_ns"])
        except (KeyError, ValueError):
            continue
    return 0.0


def pickPool(rows: list[dict], pool: int) -> dict:
    for r in rows:
        try:
            if int(r["pool_active"]) == pool:
                return r
        except (KeyError, ValueError):
            continue
    return {}


def percentileOfRevoke(rows: list[dict], pct: float) -> float:
    nss = []
    for r in rows:
        try:
            nss.append(int(r["window_ns"]))
        except (KeyError, ValueError):
            pass
    if not nss:
        return 0.0
    nss.sort()
    idx = min(int(pct * len(nss)), len(nss) - 1)
    return nss[idx]


def main() -> int:
    if len(sys.argv) != 4:
        print("usage: gen_numbers_tex.py figure1.csv pool_scaling.csv revocation.csv",
              file=sys.stderr)
        return 1

    f1   = loadCsv(Path(sys.argv[1]))
    pool = loadCsv(Path(sys.argv[2]))
    rev  = loadCsv(Path(sys.argv[3]))

    # Reference numbers.
    rawA  = pickP99(f1, "astra_raw",   256)
    gatA  = pickP99(f1, "astra_gated", 256)
    aer   = pickP99(f1, "aeron",       256)
    iour  = pickP99(f1, "io_uring",    256)
    pip   = pickP99(f1, "pipe",        256)

    # Per-message gate cost is HALF the gated-raw RTT delta: each round
    # trip validates twice (IPC_SEND at the producer, IPC_RECV at the
    # consumer). Keep in sync with the equation in sections/06_evaluation.
    delta_p99 = max(0.0, (gatA - rawA) / 2.0)
    aeron_gap = (gatA - aer) / aer * 100 if aer > 0 else 0
    # What the gate adds to the round trip, relative to the ungated path.
    # We quote this ourselves rather than let a reviewer compute it: a
    # large percentage of a very small number is still a small number,
    # and that is precisely the argument.
    gate_pct = (gatA - rawA) / rawA * 100 if rawA > 0 else 0

    pool_at_full = pickPool(pool, 4090)
    val_p50   = float(pool_at_full.get("p50_ns",   0))
    val_p99   = float(pool_at_full.get("p99_ns",   0))
    val_p9999 = float(pool_at_full.get("p9999_ns", 0))

    rev_p99_us = percentileOfRevoke(rev, 0.99) / 1000.0

    # Emit overrides. Each \renewcommand wraps the same macro defined
    # in macros.tex with a concrete value. A measurement that is absent
    # (baseline self-skipped, CSV missing) is NOT emitted — the macro
    # keeps its red [placeholder] so nobody mistakes a hole for a zero.
    print(r"% Auto-generated by scripts/gen_numbers_tex.py — do not edit.")
    print(r"% Re-run build.sh --refresh after a sweep run.")
    def emit(name: str, val: float, fmt: str = ".0f",
             present: bool | None = None) -> None:
        if present is None:
            present = val > 0
        if present:
            print(rf"\renewcommand{{\{name}}}{{{val:{fmt}}}}")
        else:
            print(rf"% \{name}: no measurement — keeping red placeholder")
    emit("validateMedian",    val_p50)
    emit("validateTail",      val_p99)
    emit("validateFourNines", val_p9999)
    emit("rawAstraRTT",   rawA)
    emit("gatedAstraRTT", gatA)
    emit("aeronRTT",      aer)
    emit("iouringRTT",    iour)
    emit("pipeRTT",       pip)
    # Deltas may legitimately be zero or negative (a negative Aeron gap
    # means we beat Aeron) — presence keys on the inputs, not the value.
    emit("gateOverheadTail", delta_p99, present=(rawA > 0 and gatA > 0))
    emit("gateOverheadPercent", gate_pct, ".0f", present=(rawA > 0 and gatA > 0))
    emit("aeronGapPercent",  aeron_gap, ".1f", present=(aer > 0 and gatA > 0))
    emit("revokeTail",       rev_p99_us, ".1f")
    return 0


if __name__ == "__main__":
    sys.exit(main())
