#!/usr/bin/env python3
# =============================================================================
# Astra Runtime - Paper 1 (USENIX ATC 2027) headline-figure plotter
# scripts/plot_paper1_figure.py
#
# Track B Sprint 7. Consumes figure_1.csv produced by run_paper1_sweep.sh
# and emits two artefacts:
#
#   1. paper1_figure_1.pdf  — log-scale p99 latency vs payload size, one
#                             line per transport. The headline figure.
#   2. paper1_table_1.tex   — \begin{tabular} block with p50/p99/p99.99
#                             across transports for the canonical 256 B
#                             payload. Drops straight into the paper.
#
# We deliberately avoid seaborn / fancy styling — Paper 1 is a systems
# paper and reviewers prefer plain matplotlib.
#
# Usage
# -----
#   python3 scripts/plot_paper1_figure.py artefact/paper1_figure_1.csv
#   python3 scripts/plot_paper1_figure.py path/to/csv --pdf out.pdf --tex out.tex
#
# Dependencies: pandas, matplotlib (both in any standard data-science env;
# pip install pandas matplotlib if missing).
# =============================================================================

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import pandas as pd
except ImportError:
    print("error: pandas not installed. pip install pandas matplotlib", file=sys.stderr)
    sys.exit(1)

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except ImportError:
    print("error: matplotlib not installed. pip install pandas matplotlib", file=sys.stderr)
    sys.exit(1)


TRANSPORT_DISPLAY = {
    "pipe":         ("pipe(2)",                 "tab:gray"),
    "socketpair":   ("AF_UNIX/SOCK_STREAM",     "tab:olive"),
    "io_uring":     ("io_uring",                "tab:blue"),
    "aeron":        ("Aeron",                   "tab:red"),
    "erpc":         ("eRPC",                    "tab:purple"),
    "astra_raw":    ("Astra (gate OFF)",        "tab:green"),
    "astra_gated":  ("Astra (capability gate ON)", "tab:orange"),
}


def loadCsv(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    # Drop SKIPPED rows
    df = df[df["payload_bytes"].astype(str) != "SKIPPED"]
    df["payload_bytes"] = df["payload_bytes"].astype(int)
    return df


def plotFigure(df: pd.DataFrame, outPdf: Path) -> None:
    fig, ax = plt.subplots(figsize=(7, 4.2))

    for transport, group in df.groupby("transport"):
        if transport not in TRANSPORT_DISPLAY:
            continue
        label, color = TRANSPORT_DISPLAY[transport]
        group = group.sort_values("payload_bytes")
        ax.plot(group["payload_bytes"],
                group["p99_ns"],
                marker="o",
                label=label,
                color=color,
                linewidth=2 if "astra" in transport else 1.2,
                linestyle="-" if "astra" in transport else "--")

    ax.set_xscale("log", base=2)
    ax.set_yscale("log")
    ax.set_xlabel("Payload size (bytes)")
    ax.set_ylabel("p99 round-trip latency (ns)")
    ax.set_title("Paper 1 Figure 1 — capability-gated IPC vs prior-art baselines")
    ax.grid(which="both", linestyle=":", linewidth=0.5, alpha=0.6)
    ax.legend(loc="upper left", framealpha=0.9, fontsize=9)

    fig.tight_layout()
    fig.savefig(outPdf, format="pdf")
    print(f"  wrote {outPdf}")


def emitTable(df: pd.DataFrame, payload: int, outTex: Path) -> None:
    sub = df[df["payload_bytes"] == payload].copy()
    if sub.empty:
        print(f"  warn: no rows at payload={payload} for table", file=sys.stderr)
        return
    rows = []
    for _, r in sub.iterrows():
        if r["transport"] not in TRANSPORT_DISPLAY:
            continue
        label = TRANSPORT_DISPLAY[r["transport"]][0]
        rows.append((label,
                     r["p50_ns"],
                     r["p99_ns"],
                     r["p9999_ns"]))

    rows.sort(key=lambda x: x[2])  # ascending by p99

    with outTex.open("w") as f:
        f.write("% Auto-generated by scripts/plot_paper1_figure.py\n")
        f.write("\\begin{tabular}{lrrr}\n")
        f.write("\\toprule\n")
        f.write(f"Transport ({payload}\\,B payload) & p50 (ns) & p99 (ns) & p99.99 (ns) \\\\\n")
        f.write("\\midrule\n")
        for label, p50, p99, p9999 in rows:
            f.write(f"{label} & {p50:.0f} & {p99:.0f} & {p9999:.0f} \\\\\n")
        f.write("\\bottomrule\n")
        f.write("\\end{tabular}\n")
    print(f"  wrote {outTex}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", type=Path)
    ap.add_argument("--pdf", type=Path,
                    default=Path("artefact/paper1_figure_1.pdf"))
    ap.add_argument("--tex", type=Path,
                    default=Path("artefact/paper1_table_1.tex"))
    ap.add_argument("--table-payload", type=int, default=256,
                    help="Payload size used for Table 1 (default 256 B)")
    args = ap.parse_args()

    args.pdf.parent.mkdir(parents=True, exist_ok=True)
    args.tex.parent.mkdir(parents=True, exist_ok=True)

    df = loadCsv(args.csv)
    if df.empty:
        print("error: csv is empty (no non-SKIPPED rows)", file=sys.stderr)
        return 1

    print(f"==> {len(df)} measurement rows across {df['transport'].nunique()} transports")
    plotFigure(df, args.pdf)
    emitTable(df, args.table_payload, args.tex)

    return 0


if __name__ == "__main__":
    sys.exit(main())
